version: '3'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
  db:
    image: postgres:13.4
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: college
    # ADICIONAR VOLUME PERSISTENTE PARA SALVAR OS DADOS AO BAIXAR O CONTAINER