version: '3'

services:
  web:
    build: .
    command: bash -c "python main.py"
    ports:
      - "80:80"
    depends_on:
      - db
    networks:
      - app-network
  db:
    image: postgres:13.4
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: college
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - app-network


volumes:
  db:

networks:
  app-network:
