version: '3'

services:
  enrollment-service:
    build: .
    command: bash -c "python main.py"
    ports:
      - "83:80"
    depends_on:
      enrollment-db:
        condition: service_healthy
    networks:
      - app-network
    healthcheck:
      test: "curl --fail http://localhost/health || exit 1"
      interval: 10s
      timeout: 5s
      retries: 3

  enrollment-db:
    image: postgres:13.4
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: enrollments
    volumes:
      - enrollment-db:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: "pg_isready -U admin -h localhost -d enrollments"
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  enrollment-db:

networks:
  app-network:
